### ISSUE TITLE
Menuconfig improvements

### ISSUE THREAD

**Issue by C47D** [lvgl/lv_port_esp32#93]
There's a lot of room for improvements to make this reference project easier to use.

**Display/touch controller configuration:**

- [x] Display pins configuration must be independent of the bus used to communicate with the display controller, I2C, SPI, etc. So if a SPI bus is used the pins to configure must be MOSI, MISO, SCLK and /SS, if I2C bus is used only SDA and SCL must be available. Fixed in #94, ef9424f
- [x] Ditto for touch controllers.
- [x] Set display rotation, see #82 and #88, Mostly fixed in #94, 900c1d1 and 42c2fd2

**LVGL configuration**
- [x] Being able to configure lvgl from the menuconfig, see #57.

Add more in the comments to add them to this task list.
